mod common;

use common::{assert_failure_contains, assert_success, run_cj, temp_path};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

struct TestRepo {
    root: PathBuf,
    work: PathBuf,
    remote: PathBuf,
}

impl TestRepo {
    fn new(version: &str) -> Self {
        let root = temp_path("release");
        let work = root.join("work");
        let remote = root.join("remote.git");
        fs::create_dir_all(&work).expect("create worktree");

        git(
            &root,
            &["init", "--bare", remote.to_str().expect("remote path")],
        );
        git(&work, &["init", "-b", "main"]);
        git(&work, &["config", "user.name", "CJTaskrunner Tests"]);
        git(
            &work,
            &["config", "user.email", "tests@cjtaskrunner.invalid"],
        );
        write_versions(&work, version);
        fs::write(work.join("README.md"), "test repository\n").expect("write readme");
        git(&work, &["add", "."]);
        git(&work, &["commit", "-m", "initial"]);
        git(
            &work,
            &[
                "remote",
                "add",
                "origin",
                remote.to_str().expect("remote path"),
            ],
        );
        git(&work, &["push", "-u", "origin", "main"]);

        Self { root, work, remote }
    }

    fn release(&self, args: &[&str]) -> Output {
        let script = Path::new(env!("CARGO_MANIFEST_DIR")).join("scripts/release-cli");
        Command::new("sh")
            .arg(script)
            .args(args)
            .current_dir(&self.work)
            .output()
            .expect("run release helper")
    }
}

impl Drop for TestRepo {
    fn drop(&mut self) {
        fs::remove_dir_all(&self.root).expect("remove test repository");
    }
}

fn git(dir: &Path, args: &[&str]) -> String {
    let output = Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .expect("run git");
    assert!(
        output.status.success(),
        "git {:?} failed\nstdout:\n{}\nstderr:\n{}",
        args,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout)
        .expect("git stdout")
        .trim()
        .to_string()
}

fn write_versions(dir: &Path, version: &str) {
    fs::write(
        dir.join("cjtasks"),
        format!("@version cli {version}\ncheck:\n  true\n"),
    )
    .expect("write cjtasks");
    fs::write(
        dir.join("Cargo.toml"),
        format!(
            "[package]\nname = \"cjtaskrunner\"\nversion = \"{version}\"\nedition = \"2021\"\n"
        ),
    )
    .expect("write Cargo.toml");
    fs::write(
        dir.join("Cargo.lock"),
        format!(
            "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"cjtaskrunner\"\nversion = \"{version}\"\n"
        ),
    )
    .expect("write Cargo.lock");
}

fn version_from_taskfile(taskfile: &str, name: &str) -> String {
    taskfile
        .lines()
        .find_map(|line| line.strip_prefix(&format!("@version {name} ")))
        .unwrap_or_else(|| panic!("missing @version {name}"))
        .to_string()
}

fn patch_bump(version: &str) -> String {
    let mut parts = version.split('.');
    let major = parts.next().expect("major version");
    let minor = parts.next().expect("minor version");
    let patch = parts
        .next()
        .expect("patch version")
        .parse::<u64>()
        .expect("numeric patch version");
    assert!(parts.next().is_none(), "expected plain semver version");
    format!("{major}.{minor}.{}", patch + 1)
}

#[test]
fn preflight_rejects_dirty_worktree() {
    let repo = TestRepo::new("0.1.0");
    fs::write(repo.work.join("README.md"), "dirty\n").expect("dirty readme");

    assert_failure_contains(&repo.release(&["preflight"]), "working tree must be clean");
}

#[test]
fn preflight_rejects_non_main_branch() {
    let repo = TestRepo::new("0.1.0");
    git(&repo.work, &["switch", "-c", "feature"]);

    assert_failure_contains(&repo.release(&["preflight"]), "must be run from main");
}

#[test]
fn verify_rejects_mismatched_versions() {
    let repo = TestRepo::new("0.1.0");
    fs::write(
        repo.work.join("Cargo.toml"),
        "[package]\nname = \"cjtaskrunner\"\nversion = \"0.1.1\"\nedition = \"2021\"\n",
    )
    .expect("write mismatched Cargo.toml");

    assert_failure_contains(
        &repo.release(&["verify", "0.1.0"]),
        "Cargo.toml version is 0.1.1, expected 0.1.0",
    );
}

#[test]
fn commit_tag_creates_annotated_tag_at_head() {
    let repo = TestRepo::new("0.1.0");
    write_versions(&repo.work, "0.1.1");

    assert_success(&repo.release(&["commit-tag", "0.1.1"]));

    assert_eq!(
        git(&repo.work, &["cat-file", "-t", "refs/tags/v0.1.1"]),
        "tag"
    );
    assert_eq!(
        git(&repo.work, &["rev-parse", "refs/tags/v0.1.1^{}"]),
        git(&repo.work, &["rev-parse", "HEAD"])
    );
    assert_eq!(
        git(&repo.work, &["show", "-s", "--format=%s", "HEAD"]),
        "Release v0.1.1"
    );
}

#[test]
fn publish_rejects_tag_not_at_head() {
    let repo = TestRepo::new("0.1.0");
    git(
        &repo.work,
        &["tag", "-a", "v0.1.0", "-m", "CJTaskrunner v0.1.0"],
    );
    fs::write(repo.work.join("README.md"), "new commit\n").expect("update readme");
    git(&repo.work, &["add", "README.md"]);
    git(&repo.work, &["commit", "-m", "later"]);

    assert_failure_contains(
        &repo.release(&["publish", "0.1.0"]),
        "tag v0.1.0 does not point to HEAD",
    );
    let remote_tag = Command::new("git")
        .args(["show-ref", "--verify", "--quiet", "refs/tags/v0.1.0"])
        .current_dir(&repo.remote)
        .status()
        .expect("check remote tag");
    assert!(!remote_tag.success());
}

#[test]
fn publish_pushes_main_and_tag_to_local_bare_remote() {
    let repo = TestRepo::new("0.1.0");
    git(
        &repo.work,
        &["tag", "-a", "v0.1.0", "-m", "CJTaskrunner v0.1.0"],
    );

    assert_success(&repo.release(&["publish", "0.1.0"]));

    assert_eq!(
        git(&repo.remote, &["rev-parse", "refs/heads/main"]),
        git(&repo.work, &["rev-parse", "HEAD"])
    );
    assert_eq!(
        git(&repo.remote, &["rev-parse", "refs/tags/v0.1.0^{}"]),
        git(&repo.work, &["rev-parse", "HEAD"])
    );
}

#[test]
fn repository_taskfile_exposes_release_tasks_and_hides_helpers() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let stdout = run_cj(root, &[]);
    assert_success(&stdout);
    let summary = String::from_utf8(stdout.stdout).expect("summary utf8");

    for task in [
        "bump ($LEVEL, $PACKAGE)",
        "release:prep ($VLEV)",
        "release:publish",
    ] {
        assert!(summary.contains(task), "summary missing {task}");
    }
    assert!(
        !summary.contains("_release:"),
        "internal release tasks must be hidden"
    );

    let source = fs::read_to_string(root.join("cjtasks")).expect("read repository cjtasks");
    assert!(
        source.contains("@task release:_checks"),
        "public release tasks must compose hidden release helpers"
    );
}

#[cfg(unix)]
#[test]
fn extension_bump_updates_extension_version_without_touching_cargo() {
    use std::os::unix::fs::PermissionsExt;

    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let dir = temp_path("extension-bump-task");
    let bin = dir.join("bin");
    fs::create_dir_all(&bin).expect("create fake bin");
    fs::create_dir_all(dir.join("editors/vscode-cjtaskrunner")).expect("create extension dir");
    let taskfile = fs::read_to_string(root.join("cjtasks")).expect("read repository cjtasks");
    let cli_version = version_from_taskfile(&taskfile, "cli");
    let next_extension_version = patch_bump(&version_from_taskfile(&taskfile, "extension"));
    fs::write(dir.join("cjtasks"), taskfile).expect("write test cjtasks");

    let fake_npm = bin.join("npm");
    fs::write(
        &fake_npm,
        r#"#!/bin/sh
set -eu
test "$1" = "version"
test "$3" = "--no-git-tag-version"
printf '%s' "$2" > npm-version.txt
"#,
    )
    .expect("write fake npm");
    let fake_cargo = bin.join("cargo");
    fs::write(
        &fake_cargo,
        r#"#!/bin/sh
printf 'cargo should not run for extension bumps\n' >&2
exit 99
"#,
    )
    .expect("write fake cargo");
    for tool in [&fake_npm, &fake_cargo] {
        let mut permissions = fs::metadata(tool)
            .expect("fake tool metadata")
            .permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(tool, permissions).expect("make fake tool executable");
    }

    let path = format!("{}:{}", bin.display(), std::env::var("PATH").expect("PATH"));
    let output = Command::new(env!("CARGO_BIN_EXE_cj"))
        .arg("bump")
        .arg("patch")
        .arg("extension")
        .current_dir(&dir)
        .env("PATH", path)
        .env("NO_COLOR", "1")
        .output()
        .expect("run extension bump task");
    assert_success(&output);

    assert_eq!(
        fs::read_to_string(dir.join("editors/vscode-cjtaskrunner/npm-version.txt"))
            .expect("npm version"),
        next_extension_version
    );
    let updated_taskfile = fs::read_to_string(dir.join("cjtasks")).expect("updated cjtasks");
    assert!(updated_taskfile.contains(&format!("@version cli {cli_version}")));
    assert!(updated_taskfile.contains(&format!("@version extension {next_extension_version}")));

    fs::remove_dir_all(dir).expect("remove extension bump task repository");
}

#[test]
fn github_workflow_publishes_verified_cli_tags() {
    let workflow = fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join(".github/workflows/build.yml"),
    )
    .expect("read build workflow");

    for required in [
        "tags:",
        "GITHUB_REF_NAME",
        "cargo metadata --no-deps --format-version 1",
        "macos-15-intel",
        "x86_64-apple-darwin",
        "aarch64-apple-darwin",
        "timeout-minutes: 15",
        "cancel-in-progress: true",
        "cargo build --release --locked --bin cj --target ${{ matrix.target }}",
        "actions/upload-artifact@",
        "actions/download-artifact@",
        "SHA256SUMS",
        "contents: write",
        "GH_REPO: ${{ github.repository }}",
        "gh release create",
        "--verify-tag",
        "startsWith(github.ref, 'refs/tags/v')",
    ] {
        assert!(
            workflow.contains(required),
            "workflow missing required release fragment: {required}"
        );
    }
    assert!(
        !workflow.contains("macos-13"),
        "workflow must not use the retired macos-13 runner"
    );
    for suspended in ["windows-latest", "x86_64-pc-windows-msvc", "windows-x86_64"] {
        assert!(
            !workflow.contains(suspended),
            "workflow must not publish suspended Windows artifact: {suspended}"
        );
    }
}
