[book]
title = "CJTaskrunner"
description = "CJTaskrunner language and project documentation"
src = "src"

[output.html]
theme = "theme"
default-theme = "dark"
preferred-dark-theme = "CJTaskrunner"
additional-css = ["theme/cjtaskrunner.css"]
additional-js = ["theme/cjtaskrunner.js"]
git-repository-url = "https://github.com/jgusta/cjtaskrunner"
site-url = "/cjtaskrunner/"
# no-section-label = true
sidebar-header-nav = true

[output.html.search]
enable = true
use-boolean-and = true
heading-split-level = 3
